### ISSUE TITLE
timeout on wheel upload

### ISSUE THREAD

**Issue by ldgeo** [rcommande/papaye#4]
Hi Romain, 

when i try to upload some wheels, nothing happens on the server side, no logs, i've tried in development mode but no more output !
```
$ twine upload -r papaye *.whl
Uploading distributions to http://localhost:6543/simple/
Uploading aniso8601-1.1.0-py2-none-any.whl
``` 
Any ideas ?

**Comment by rcommande** [comment]
Hi! Which version do you use ? 0.2.2 ?

**Comment by ldgeo** [comment]
Yes, latest release

**Comment by rcommande** [comment]
And with `python setup.py upload` ?

**Comment by ldgeo** [comment]
It works with setup.py but i wanted to upload a bunch of wheels at the same time.
Ok so the problem is twine... i've tested the latest version no more luck.
In fact twine only allows ssl connections so it doesn't work on local pypi, i had to hack twine a little bit to pass ```verify=False``` on the requests session.
After that it works great !
